name: msaudit
description: "A smartinfraco audit app to check engineers on their project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  image: ^4.2.0
  flutter_lints: ^3.0.0
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  path_provider: ^2.1.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgroundmsa.png
    - assets/logomsa.png
    - assets/MSA.png
    - assets/
    - assets/checklist.json
    
